version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17  # Using a CircleCI maintained Go image

    working_directory: /go/src/github.com/aswinbennyofficial/circleci-playground

    steps:
      - checkout

      # Run Go tests
      - run:
          name: Run Go tests
          command: go test ./...

      # Use setup_remote_docker to set up a remote Docker environment
      - setup_remote_docker

      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t breeze5690/hello-world:latest .

      # Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: docker push breeze5690/hello-world:latest

workflows:
  version: 2
  build:
    jobs:
      - build
