version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17  # Using a CircleCI maintained Go image

    working_directory: ~/circleci-playground  # Assuming the project directory is mapped to this path

    steps:
      - checkout

      # Run Go tests
      - run:
          name: Run Go tests
          command: go test ./...  # Include coverage for better feedback (optional)

      # Use setup_remote_docker to set up a remote Docker environment
      - setup_remote_docker

      # Build Docker image (assuming Dockerfile is in the project root)
      - run:
          name: Build Docker image
          command: docker build -t breeze5690/hello-world:latest .

      # Login to Docker Hub using environment variables
      - run:
          name: Login to Docker Hub
          command: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: docker push breeze5690/hello-world:latest

workflows:
  version: 2
  build:
    jobs:
      - build
