version: 2.1

jobs:
  build:
    docker:
      - image: docker:19.03.12

    working_directory: /go/src/github.com/aswinbennyofficial/circleci-playground

    steps:
      - checkout

      # Install Go (if needed)
      - run:
          name: Install Go
          command: apk add --no-cache go

      # Run Go tests
      - run:
          name: Run Go tests
          command: go test ./...

      # Install Docker client
      - run:
          name: Install Docker client
          command: apk add --no-cache docker

      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t breeze5690/hello-world:latest .

      # Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: docker push breeze5690/hello-world:latest

workflows:
  version: 2
  build:
    jobs:
      - build
